doc_structure_test = {
    {'content': 'Company Overview', 'level': 1, 'type': 'title'},
                      {'content': '**Company Overview**\n'
                                  '\n'
                                  'NVIDIA Corporation is a leading technology company in the '
                                  'semiconductor and graphics processing unit (GPU) industry. The '
                                  'company is known for its innovative products and solutions in '
                                  'the technology sector. NVIDIA Corporation has established itself '
                                  'as a key player in the industry, providing cutting-edge '
                                  'technology to a wide range of customers.',
                       'description': 'Provides an overview of the company.',
                       'prompts': ['What is the company name?', 'What is the company industry?'],
                       'type': 'text'},
                      {'content': 'Market Analysis', 'level': 1, 'type': 'title'},
                      {'content': '**Company Overview**\n'
                                  '\n'
                                  'NVIDIA Corporation is a leading technology company in the '
                                  'semiconductor and graphics processing unit (GPU) industry. The '
                                  'company caters to a diverse range of industries, including '
                                  'gaming, artificial intelligence, data centers, automotive, and '
                                  'professional visualization. NVIDIA provides high-performance '
                                  'computing, graphics processing, and artificial intelligence '
                                  'solutions tailored to the specific needs of each industry.\n'
                                  '\n'
                                  '**Target Market**\n'
                                  '\n'
                                  "NVIDIA Corporation's target market encompasses various sectors, "
                                  'including:\n'
                                  '- Gaming industry\n'
                                  '- Artificial intelligence sector\n'
                                  '- Data centers\n'
                                  '- Automotive industry\n'
                                  '- Professional visualization\n'
                                  '\n'
                                  'The company offers products and solutions that meet the high '
                                  'demands of these industries, providing cutting-edge technology '
                                  'for enhanced performance and efficiency.\n'
                                  '\n'
                                  'For further details, please refer to the investment memo '
                                  'available in the output repository.',
                       'description': 'Provides an analysis of the market.',
                       'prompts': ["What is the company's target market?",
                                   'Generate the investment memo.'],
                       'type': 'text'},
                      {'content': 'Product or Service Analysis', 'level': 1, 'type': 'title'},
                      {'content': '## Company Overview\n'
                                  '\n'
                                  '**Company Name:** NVIDIA Corporation\n'
                                  '\n'
                                  '**Industry:** Technology, specializing in the semiconductor and '
                                  'graphics processing unit (GPU) industry\n'
                                  '\n'
                                  "**Target Market:** NVIDIA Corporation's target market includes "
                                  'industries such as gaming, artificial intelligence, data '
                                  'centers, automotive, and professional visualization. They '
                                  'provide high-performance computing, graphics processing, and '
                                  'artificial intelligence solutions for these industries.\n'
                                  '\n'
                                  '## Key Products and Services\n'
                                  '\n'
                                  '1. **Graphics Processing Units (GPUs):** Used in gaming, '
                                  'professional visualization, data centers, and artificial '
                                  'intelligence applications.\n'
                                  '   \n'
                                  '2. **Data Center Solutions:** Leveraging GPUs for '
                                  'high-performance computing, deep learning, and artificial '
                                  'intelligence workloads.\n'
                                  '   \n'
                                  '3. **Gaming Products:** Graphics cards for gaming enthusiasts, '
                                  'including the popular GeForce series.\n'
                                  '   \n'
                                  '4. **Professional Visualization Solutions:** Professional-grade '
                                  'GPUs for 3D rendering, virtual reality, and design work.\n'
                                  '   \n'
                                  '5. **Automotive Solutions:** Hardware and software for '
                                  'autonomous driving, in-car infotainment systems, and advanced '
                                  'driver assistance systems.\n'
                                  '   \n'
                                  '6. **Artificial Intelligence Platforms:** AI platforms like the '
                                  'NVIDIA Tesla series for deep learning, machine learning, and AI '
                                  'research.\n'
                                  '\n'
                                  '## Unique Selling Points (USPs)\n'
                                  '\n'
                                  '1. **High-Performance GPUs:** Known for efficiency, cutting-edge '
                                  'technology, and superior computing power.\n'
                                  '   \n'
                                  '2. **AI and Deep Learning Capabilities:** Leader in AI and deep '
                                  'learning technologies.\n'
                                  '   \n'
                                  '3. **Industry-Leading Graphics Technology:** Renowned for '
                                  'realism, speed, and quality.\n'
                                  '   \n'
                                  '4. **Data Center Solutions:** Scalable, efficient, and '
                                  'accelerated computing capabilities.\n'
                                  '   \n'
                                  '5. **Automotive Innovation:** Driving the future of '
                                  'transportation and automotive safety.\n'
                                  '   \n'
                                  '6. **Ecosystem and Partnerships:** Strong partnerships driving '
                                  'innovation and industry advancements.\n'
                                  '\n'
                                  '## Product and Service Development Plans\n'
                                  '\n'
                                  '1. **Advancements in GPU Technology:** Research and development '
                                  'for next-gen GPUs.\n'
                                  '   \n'
                                  '2. **Expansion of AI and Deep Learning Solutions:** Developing '
                                  'new AI platforms and tools.\n'
                                  '   \n'
                                  '3. **Data Center Innovation:** Developing GPU-accelerated '
                                  'computing technologies.\n'
                                  '   \n'
                                  '4. **Automotive Technology Advancements:** Improving hardware '
                                  'and software for automotive solutions.\n'
                                  '   \n'
                                  '5. **Gaming and Professional Visualization Enhancements:** '
                                  'Improving graphics performance and user experiences.\n'
                                  '   \n'
                                  '6. **Expansion of Ecosystem and Partnerships:** Forming '
                                  'strategic partnerships for innovation.\n'
                                  '\n'
                                  '## Pricing Strategies\n'
                                  '\n'
                                  '1. **Value-Based Pricing:** Setting prices based on perceived '
                                  'value.\n'
                                  '   \n'
                                  '2. **Skimming Pricing:** Setting high initial prices for '
                                  'innovative technologies.\n'
                                  '   \n'
                                  '3. **Penetration Pricing:** Setting low prices to gain market '
                                  'share.\n'
                                  '   \n'
                                  '4. **Bundle Pricing:** Offering bundled products at discounted '
                                  'prices.\n'
                                  '   \n'
                                  '5. **Freemium Pricing:** Offering basic features for free with '
                                  'premium upgrades.\n'
                                  '   \n'
                                  '6. **Competitive Pricing:** Adjusting prices based on '
                                  "competitors' strategies.\n"
                                  '\n'
                                  '## Distribution Channels\n'
                                  '\n'
                                  '1. **Direct Sales:** Online store, retail outlets, and sales '
                                  'representatives.\n'
                                  '   \n'
                                  '2. **Retail Partners:** Partnerships with retail outlets and '
                                  'online retailers.\n'
                                  '   \n'
                                  '3. **System Integrators and OEMs:** Collaboration with hardware '
                                  'partners.\n'
                                  '   \n'
                                  '4. **Channel Partners and Distributors:** Working with resellers '
                                  'and distributors.\n'
                                  '   \n'
                                  '5. **Cloud Service Providers:** Partnerships for cloud-based '
                                  'services.\n'
                                  '   \n'
                                  '6. **Developer Community:** Engaging with developers through '
                                  'programs.\n'
                                  '   \n'
                                  '7. **Online Platforms and Marketplaces:** Leveraging online '
                                  'platforms for global reach.',
                       'description': "Provides an analysis of the company's products or services.",
                       'prompts': ["What are the company's key products or services?",
                                   "What are the unique selling points (USPs) of the company's "
                                   'products or services?',
                                   'What are the product or service development plans?',
                                   'What are the product or service pricing strategies?',
                                   'What are the product or service distribution channels?'],
                       'type': 'text'}
}
